#!/bin/sh
rel=$1.tar.gz
rf=/tmp/$rel
if echo $rel | grep -q - ; then
	echo "Uploading $rel (ALPHA)"
	alpha=alpha/
else
	echo "Uploading $rel"
	alpha=
fi
echo "atrey"
scp $rf README pciutils.lsm atrey:~ftp/pub/linux/pci/$alpha
echo "kernel.org"
scp $rf README pciutils.lsm master.kernel.org:~ftp/pub/software/utils/pciutils/$alpha
if [ -z "$alpha" ] ; then
	echo "metalab"
	ftp -v metalab.unc.edu <<EOF
cd incoming/Linux
put $rf $rel
put pciutils.lsm
quit
EOF
	fi
echo "jabberwock"
scp -C pci.ids pciids@jabberwock.ucw.cz:origs/05-$1
